_homepage:
    path:     /{_locale}
    defaults: { _controller: AppBundle:Default:index, _locale: en }
    requirements:
            _locale: en|es|it

_booking:
    path:     /{_locale}/booking/{id}
    defaults: { _controller: AppBundle:Default:login , _locale: en}
    requirements:
            _locale: en|es|it

_hotels:
    path:     /{_locale}/config/hotels
    defaults: { _controller: AppBundle:Hotel:hotels, _locale: en }
    requirements:
            _locale: en|es|it

_hotels_create:
    path:     /{_locale}/config/hotel/new
    defaults: { _controller: AppBundle:Hotel:new, _locale: en }
    requirements:
            _locale: en|es|it

_hotels_edit:
    path:     /{_locale}/config/hotel/{id}
    defaults: { _controller: AppBundle:Hotel:edit, _locale: en }
    requirements:
            _locale: en|es|it

_hotels_delete:
    path:     /{_locale}/config/hotel/delete/{id}
    defaults: { _controller: AppBundle:Hotel:hotelDelete, _locale: en }
    requirements:
            _locale: en|es|it

_services:
    path:     /services
    defaults: { _controller: AppBundle:Config:services }

_rooms:
    path:     /rooms
    defaults: { _controller: AppBundle:Config:rooms }

_roomtypes:
    path:     /roomtypes
    defaults: { _controller: AppBundle:Config:roomtypes }

_offers:
    path:     /offers
    defaults: { _controller: AppBundle:Config:offers }

_rates:
    path:     /rates
    defaults: { _controller: AppBundle:Config:rates }
